/*
Api Documentation

Testing SearchControllerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package atapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_atapi_SearchControllerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SearchControllerAPIService MultiSearchUsingGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var searchString string

		resp, httpRes, err := apiClient.SearchControllerAPI.MultiSearchUsingGET(context.Background(), searchString).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
