/*
Api Documentation

Api Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atapi

import (
	"encoding/json"
)

// checks if the CompanyAchievementView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyAchievementView{}

// CompanyAchievementView struct for CompanyAchievementView
type CompanyAchievementView struct {
	AchievedDate *int64 `json:"achievedDate,omitempty"`
	Claimed *bool `json:"claimed,omitempty"`
	CoinReward *int64 `json:"coinReward,omitempty"`
	Company *CompactCompanyView `json:"company,omitempty"`
	Description *string `json:"description,omitempty"`
	EndDate *int64 `json:"endDate,omitempty"`
	Id *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	Version *int64 `json:"version,omitempty"`
}

// NewCompanyAchievementView instantiates a new CompanyAchievementView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyAchievementView() *CompanyAchievementView {
	this := CompanyAchievementView{}
	return &this
}

// NewCompanyAchievementViewWithDefaults instantiates a new CompanyAchievementView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyAchievementViewWithDefaults() *CompanyAchievementView {
	this := CompanyAchievementView{}
	return &this
}

// GetAchievedDate returns the AchievedDate field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetAchievedDate() int64 {
	if o == nil || IsNil(o.AchievedDate) {
		var ret int64
		return ret
	}
	return *o.AchievedDate
}

// GetAchievedDateOk returns a tuple with the AchievedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetAchievedDateOk() (*int64, bool) {
	if o == nil || IsNil(o.AchievedDate) {
		return nil, false
	}
	return o.AchievedDate, true
}

// HasAchievedDate returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasAchievedDate() bool {
	if o != nil && !IsNil(o.AchievedDate) {
		return true
	}

	return false
}

// SetAchievedDate gets a reference to the given int64 and assigns it to the AchievedDate field.
func (o *CompanyAchievementView) SetAchievedDate(v int64) {
	o.AchievedDate = &v
}

// GetClaimed returns the Claimed field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetClaimed() bool {
	if o == nil || IsNil(o.Claimed) {
		var ret bool
		return ret
	}
	return *o.Claimed
}

// GetClaimedOk returns a tuple with the Claimed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetClaimedOk() (*bool, bool) {
	if o == nil || IsNil(o.Claimed) {
		return nil, false
	}
	return o.Claimed, true
}

// HasClaimed returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasClaimed() bool {
	if o != nil && !IsNil(o.Claimed) {
		return true
	}

	return false
}

// SetClaimed gets a reference to the given bool and assigns it to the Claimed field.
func (o *CompanyAchievementView) SetClaimed(v bool) {
	o.Claimed = &v
}

// GetCoinReward returns the CoinReward field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetCoinReward() int64 {
	if o == nil || IsNil(o.CoinReward) {
		var ret int64
		return ret
	}
	return *o.CoinReward
}

// GetCoinRewardOk returns a tuple with the CoinReward field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetCoinRewardOk() (*int64, bool) {
	if o == nil || IsNil(o.CoinReward) {
		return nil, false
	}
	return o.CoinReward, true
}

// HasCoinReward returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasCoinReward() bool {
	if o != nil && !IsNil(o.CoinReward) {
		return true
	}

	return false
}

// SetCoinReward gets a reference to the given int64 and assigns it to the CoinReward field.
func (o *CompanyAchievementView) SetCoinReward(v int64) {
	o.CoinReward = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetCompany() CompactCompanyView {
	if o == nil || IsNil(o.Company) {
		var ret CompactCompanyView
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetCompanyOk() (*CompactCompanyView, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given CompactCompanyView and assigns it to the Company field.
func (o *CompanyAchievementView) SetCompany(v CompactCompanyView) {
	o.Company = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CompanyAchievementView) SetDescription(v string) {
	o.Description = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetEndDate() int64 {
	if o == nil || IsNil(o.EndDate) {
		var ret int64
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetEndDateOk() (*int64, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given int64 and assigns it to the EndDate field.
func (o *CompanyAchievementView) SetEndDate(v int64) {
	o.EndDate = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CompanyAchievementView) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CompanyAchievementView) SetType(v string) {
	o.Type = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CompanyAchievementView) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAchievementView) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CompanyAchievementView) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *CompanyAchievementView) SetVersion(v int64) {
	o.Version = &v
}

func (o CompanyAchievementView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyAchievementView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AchievedDate) {
		toSerialize["achievedDate"] = o.AchievedDate
	}
	if !IsNil(o.Claimed) {
		toSerialize["claimed"] = o.Claimed
	}
	if !IsNil(o.CoinReward) {
		toSerialize["coinReward"] = o.CoinReward
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableCompanyAchievementView struct {
	value *CompanyAchievementView
	isSet bool
}

func (v NullableCompanyAchievementView) Get() *CompanyAchievementView {
	return v.value
}

func (v *NullableCompanyAchievementView) Set(val *CompanyAchievementView) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyAchievementView) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyAchievementView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyAchievementView(val *CompanyAchievementView) *NullableCompanyAchievementView {
	return &NullableCompanyAchievementView{value: val, isSet: true}
}

func (v NullableCompanyAchievementView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyAchievementView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


