/*
Api Documentation

Api Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atapi

import (
	"encoding/json"
)

// checks if the MainInterestRateView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MainInterestRateView{}

// MainInterestRateView struct for MainInterestRateView
type MainInterestRateView struct {
	Date *int64 `json:"date,omitempty"`
	Id *string `json:"id,omitempty"`
	ReserveInterestRate *float32 `json:"reserveInterestRate,omitempty"`
	Value *float32 `json:"value,omitempty"`
	Version *int64 `json:"version,omitempty"`
}

// NewMainInterestRateView instantiates a new MainInterestRateView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainInterestRateView() *MainInterestRateView {
	this := MainInterestRateView{}
	return &this
}

// NewMainInterestRateViewWithDefaults instantiates a new MainInterestRateView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainInterestRateViewWithDefaults() *MainInterestRateView {
	this := MainInterestRateView{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *MainInterestRateView) GetDate() int64 {
	if o == nil || IsNil(o.Date) {
		var ret int64
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainInterestRateView) GetDateOk() (*int64, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *MainInterestRateView) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given int64 and assigns it to the Date field.
func (o *MainInterestRateView) SetDate(v int64) {
	o.Date = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MainInterestRateView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainInterestRateView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MainInterestRateView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MainInterestRateView) SetId(v string) {
	o.Id = &v
}

// GetReserveInterestRate returns the ReserveInterestRate field value if set, zero value otherwise.
func (o *MainInterestRateView) GetReserveInterestRate() float32 {
	if o == nil || IsNil(o.ReserveInterestRate) {
		var ret float32
		return ret
	}
	return *o.ReserveInterestRate
}

// GetReserveInterestRateOk returns a tuple with the ReserveInterestRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainInterestRateView) GetReserveInterestRateOk() (*float32, bool) {
	if o == nil || IsNil(o.ReserveInterestRate) {
		return nil, false
	}
	return o.ReserveInterestRate, true
}

// HasReserveInterestRate returns a boolean if a field has been set.
func (o *MainInterestRateView) HasReserveInterestRate() bool {
	if o != nil && !IsNil(o.ReserveInterestRate) {
		return true
	}

	return false
}

// SetReserveInterestRate gets a reference to the given float32 and assigns it to the ReserveInterestRate field.
func (o *MainInterestRateView) SetReserveInterestRate(v float32) {
	o.ReserveInterestRate = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MainInterestRateView) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainInterestRateView) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MainInterestRateView) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *MainInterestRateView) SetValue(v float32) {
	o.Value = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *MainInterestRateView) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainInterestRateView) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *MainInterestRateView) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *MainInterestRateView) SetVersion(v int64) {
	o.Version = &v
}

func (o MainInterestRateView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MainInterestRateView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ReserveInterestRate) {
		toSerialize["reserveInterestRate"] = o.ReserveInterestRate
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableMainInterestRateView struct {
	value *MainInterestRateView
	isSet bool
}

func (v NullableMainInterestRateView) Get() *MainInterestRateView {
	return v.value
}

func (v *NullableMainInterestRateView) Set(val *MainInterestRateView) {
	v.value = val
	v.isSet = true
}

func (v NullableMainInterestRateView) IsSet() bool {
	return v.isSet
}

func (v *NullableMainInterestRateView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainInterestRateView(val *MainInterestRateView) *NullableMainInterestRateView {
	return &NullableMainInterestRateView{value: val, isSet: true}
}

func (v NullableMainInterestRateView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainInterestRateView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


