/*
Api Documentation

Api Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atapi

import (
	"encoding/json"
)

// checks if the AllianceAchievementView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllianceAchievementView{}

// AllianceAchievementView struct for AllianceAchievementView
type AllianceAchievementView struct {
	AchievedDate *int64 `json:"achievedDate,omitempty"`
	Alliance *AllianceView `json:"alliance,omitempty"`
	Claimed *bool `json:"claimed,omitempty"`
	CoinReward *int64 `json:"coinReward,omitempty"`
	Description *string `json:"description,omitempty"`
	EndDate *int64 `json:"endDate,omitempty"`
	Id *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	Version *int64 `json:"version,omitempty"`
}

// NewAllianceAchievementView instantiates a new AllianceAchievementView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllianceAchievementView() *AllianceAchievementView {
	this := AllianceAchievementView{}
	return &this
}

// NewAllianceAchievementViewWithDefaults instantiates a new AllianceAchievementView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllianceAchievementViewWithDefaults() *AllianceAchievementView {
	this := AllianceAchievementView{}
	return &this
}

// GetAchievedDate returns the AchievedDate field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetAchievedDate() int64 {
	if o == nil || IsNil(o.AchievedDate) {
		var ret int64
		return ret
	}
	return *o.AchievedDate
}

// GetAchievedDateOk returns a tuple with the AchievedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetAchievedDateOk() (*int64, bool) {
	if o == nil || IsNil(o.AchievedDate) {
		return nil, false
	}
	return o.AchievedDate, true
}

// HasAchievedDate returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasAchievedDate() bool {
	if o != nil && !IsNil(o.AchievedDate) {
		return true
	}

	return false
}

// SetAchievedDate gets a reference to the given int64 and assigns it to the AchievedDate field.
func (o *AllianceAchievementView) SetAchievedDate(v int64) {
	o.AchievedDate = &v
}

// GetAlliance returns the Alliance field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetAlliance() AllianceView {
	if o == nil || IsNil(o.Alliance) {
		var ret AllianceView
		return ret
	}
	return *o.Alliance
}

// GetAllianceOk returns a tuple with the Alliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetAllianceOk() (*AllianceView, bool) {
	if o == nil || IsNil(o.Alliance) {
		return nil, false
	}
	return o.Alliance, true
}

// HasAlliance returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasAlliance() bool {
	if o != nil && !IsNil(o.Alliance) {
		return true
	}

	return false
}

// SetAlliance gets a reference to the given AllianceView and assigns it to the Alliance field.
func (o *AllianceAchievementView) SetAlliance(v AllianceView) {
	o.Alliance = &v
}

// GetClaimed returns the Claimed field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetClaimed() bool {
	if o == nil || IsNil(o.Claimed) {
		var ret bool
		return ret
	}
	return *o.Claimed
}

// GetClaimedOk returns a tuple with the Claimed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetClaimedOk() (*bool, bool) {
	if o == nil || IsNil(o.Claimed) {
		return nil, false
	}
	return o.Claimed, true
}

// HasClaimed returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasClaimed() bool {
	if o != nil && !IsNil(o.Claimed) {
		return true
	}

	return false
}

// SetClaimed gets a reference to the given bool and assigns it to the Claimed field.
func (o *AllianceAchievementView) SetClaimed(v bool) {
	o.Claimed = &v
}

// GetCoinReward returns the CoinReward field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetCoinReward() int64 {
	if o == nil || IsNil(o.CoinReward) {
		var ret int64
		return ret
	}
	return *o.CoinReward
}

// GetCoinRewardOk returns a tuple with the CoinReward field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetCoinRewardOk() (*int64, bool) {
	if o == nil || IsNil(o.CoinReward) {
		return nil, false
	}
	return o.CoinReward, true
}

// HasCoinReward returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasCoinReward() bool {
	if o != nil && !IsNil(o.CoinReward) {
		return true
	}

	return false
}

// SetCoinReward gets a reference to the given int64 and assigns it to the CoinReward field.
func (o *AllianceAchievementView) SetCoinReward(v int64) {
	o.CoinReward = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AllianceAchievementView) SetDescription(v string) {
	o.Description = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetEndDate() int64 {
	if o == nil || IsNil(o.EndDate) {
		var ret int64
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetEndDateOk() (*int64, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given int64 and assigns it to the EndDate field.
func (o *AllianceAchievementView) SetEndDate(v int64) {
	o.EndDate = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AllianceAchievementView) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AllianceAchievementView) SetType(v string) {
	o.Type = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AllianceAchievementView) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllianceAchievementView) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AllianceAchievementView) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *AllianceAchievementView) SetVersion(v int64) {
	o.Version = &v
}

func (o AllianceAchievementView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllianceAchievementView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AchievedDate) {
		toSerialize["achievedDate"] = o.AchievedDate
	}
	if !IsNil(o.Alliance) {
		toSerialize["alliance"] = o.Alliance
	}
	if !IsNil(o.Claimed) {
		toSerialize["claimed"] = o.Claimed
	}
	if !IsNil(o.CoinReward) {
		toSerialize["coinReward"] = o.CoinReward
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableAllianceAchievementView struct {
	value *AllianceAchievementView
	isSet bool
}

func (v NullableAllianceAchievementView) Get() *AllianceAchievementView {
	return v.value
}

func (v *NullableAllianceAchievementView) Set(val *AllianceAchievementView) {
	v.value = val
	v.isSet = true
}

func (v NullableAllianceAchievementView) IsSet() bool {
	return v.isSet
}

func (v *NullableAllianceAchievementView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllianceAchievementView(val *AllianceAchievementView) *NullableAllianceAchievementView {
	return &NullableAllianceAchievementView{value: val, isSet: true}
}

func (v NullableAllianceAchievementView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllianceAchievementView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


