/*
Api Documentation

Api Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atapi

import (
	"encoding/json"
)

// checks if the CompanyInterest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyInterest{}

// CompanyInterest struct for CompanyInterest
type CompanyInterest struct {
	CompanyId *string `json:"companyId,omitempty"`
	Id *string `json:"id,omitempty"`
	Interest *int64 `json:"interest,omitempty"`
	UserId *string `json:"userId,omitempty"`
	Version *int64 `json:"version,omitempty"`
}

// NewCompanyInterest instantiates a new CompanyInterest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyInterest() *CompanyInterest {
	this := CompanyInterest{}
	return &this
}

// NewCompanyInterestWithDefaults instantiates a new CompanyInterest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyInterestWithDefaults() *CompanyInterest {
	this := CompanyInterest{}
	return &this
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *CompanyInterest) GetCompanyId() string {
	if o == nil || IsNil(o.CompanyId) {
		var ret string
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyInterest) GetCompanyIdOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *CompanyInterest) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given string and assigns it to the CompanyId field.
func (o *CompanyInterest) SetCompanyId(v string) {
	o.CompanyId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CompanyInterest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyInterest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CompanyInterest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CompanyInterest) SetId(v string) {
	o.Id = &v
}

// GetInterest returns the Interest field value if set, zero value otherwise.
func (o *CompanyInterest) GetInterest() int64 {
	if o == nil || IsNil(o.Interest) {
		var ret int64
		return ret
	}
	return *o.Interest
}

// GetInterestOk returns a tuple with the Interest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyInterest) GetInterestOk() (*int64, bool) {
	if o == nil || IsNil(o.Interest) {
		return nil, false
	}
	return o.Interest, true
}

// HasInterest returns a boolean if a field has been set.
func (o *CompanyInterest) HasInterest() bool {
	if o != nil && !IsNil(o.Interest) {
		return true
	}

	return false
}

// SetInterest gets a reference to the given int64 and assigns it to the Interest field.
func (o *CompanyInterest) SetInterest(v int64) {
	o.Interest = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CompanyInterest) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyInterest) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CompanyInterest) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *CompanyInterest) SetUserId(v string) {
	o.UserId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CompanyInterest) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyInterest) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CompanyInterest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *CompanyInterest) SetVersion(v int64) {
	o.Version = &v
}

func (o CompanyInterest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyInterest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompanyId) {
		toSerialize["companyId"] = o.CompanyId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Interest) {
		toSerialize["interest"] = o.Interest
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableCompanyInterest struct {
	value *CompanyInterest
	isSet bool
}

func (v NullableCompanyInterest) Get() *CompanyInterest {
	return v.value
}

func (v *NullableCompanyInterest) Set(val *CompanyInterest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyInterest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyInterest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyInterest(val *CompanyInterest) *NullableCompanyInterest {
	return &NullableCompanyInterest{value: val, isSet: true}
}

func (v NullableCompanyInterest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyInterest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


