/*
Api Documentation

Api Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atapi

import (
	"encoding/json"
)

// checks if the MessageBoardMembershipView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageBoardMembershipView{}

// MessageBoardMembershipView struct for MessageBoardMembershipView
type MessageBoardMembershipView struct {
	Id *string `json:"id,omitempty"`
	Member *UsernameView `json:"member,omitempty"`
	MessageBoard *MessageBoardView `json:"messageBoard,omitempty"`
	Online *bool `json:"online,omitempty"`
	Role *string `json:"role,omitempty"`
	Version *int64 `json:"version,omitempty"`
}

// NewMessageBoardMembershipView instantiates a new MessageBoardMembershipView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageBoardMembershipView() *MessageBoardMembershipView {
	this := MessageBoardMembershipView{}
	return &this
}

// NewMessageBoardMembershipViewWithDefaults instantiates a new MessageBoardMembershipView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageBoardMembershipViewWithDefaults() *MessageBoardMembershipView {
	this := MessageBoardMembershipView{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MessageBoardMembershipView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageBoardMembershipView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MessageBoardMembershipView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MessageBoardMembershipView) SetId(v string) {
	o.Id = &v
}

// GetMember returns the Member field value if set, zero value otherwise.
func (o *MessageBoardMembershipView) GetMember() UsernameView {
	if o == nil || IsNil(o.Member) {
		var ret UsernameView
		return ret
	}
	return *o.Member
}

// GetMemberOk returns a tuple with the Member field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageBoardMembershipView) GetMemberOk() (*UsernameView, bool) {
	if o == nil || IsNil(o.Member) {
		return nil, false
	}
	return o.Member, true
}

// HasMember returns a boolean if a field has been set.
func (o *MessageBoardMembershipView) HasMember() bool {
	if o != nil && !IsNil(o.Member) {
		return true
	}

	return false
}

// SetMember gets a reference to the given UsernameView and assigns it to the Member field.
func (o *MessageBoardMembershipView) SetMember(v UsernameView) {
	o.Member = &v
}

// GetMessageBoard returns the MessageBoard field value if set, zero value otherwise.
func (o *MessageBoardMembershipView) GetMessageBoard() MessageBoardView {
	if o == nil || IsNil(o.MessageBoard) {
		var ret MessageBoardView
		return ret
	}
	return *o.MessageBoard
}

// GetMessageBoardOk returns a tuple with the MessageBoard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageBoardMembershipView) GetMessageBoardOk() (*MessageBoardView, bool) {
	if o == nil || IsNil(o.MessageBoard) {
		return nil, false
	}
	return o.MessageBoard, true
}

// HasMessageBoard returns a boolean if a field has been set.
func (o *MessageBoardMembershipView) HasMessageBoard() bool {
	if o != nil && !IsNil(o.MessageBoard) {
		return true
	}

	return false
}

// SetMessageBoard gets a reference to the given MessageBoardView and assigns it to the MessageBoard field.
func (o *MessageBoardMembershipView) SetMessageBoard(v MessageBoardView) {
	o.MessageBoard = &v
}

// GetOnline returns the Online field value if set, zero value otherwise.
func (o *MessageBoardMembershipView) GetOnline() bool {
	if o == nil || IsNil(o.Online) {
		var ret bool
		return ret
	}
	return *o.Online
}

// GetOnlineOk returns a tuple with the Online field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageBoardMembershipView) GetOnlineOk() (*bool, bool) {
	if o == nil || IsNil(o.Online) {
		return nil, false
	}
	return o.Online, true
}

// HasOnline returns a boolean if a field has been set.
func (o *MessageBoardMembershipView) HasOnline() bool {
	if o != nil && !IsNil(o.Online) {
		return true
	}

	return false
}

// SetOnline gets a reference to the given bool and assigns it to the Online field.
func (o *MessageBoardMembershipView) SetOnline(v bool) {
	o.Online = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *MessageBoardMembershipView) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageBoardMembershipView) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *MessageBoardMembershipView) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *MessageBoardMembershipView) SetRole(v string) {
	o.Role = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *MessageBoardMembershipView) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageBoardMembershipView) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *MessageBoardMembershipView) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *MessageBoardMembershipView) SetVersion(v int64) {
	o.Version = &v
}

func (o MessageBoardMembershipView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageBoardMembershipView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Member) {
		toSerialize["member"] = o.Member
	}
	if !IsNil(o.MessageBoard) {
		toSerialize["messageBoard"] = o.MessageBoard
	}
	if !IsNil(o.Online) {
		toSerialize["online"] = o.Online
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableMessageBoardMembershipView struct {
	value *MessageBoardMembershipView
	isSet bool
}

func (v NullableMessageBoardMembershipView) Get() *MessageBoardMembershipView {
	return v.value
}

func (v *NullableMessageBoardMembershipView) Set(val *MessageBoardMembershipView) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageBoardMembershipView) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageBoardMembershipView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageBoardMembershipView(val *MessageBoardMembershipView) *NullableMessageBoardMembershipView {
	return &NullableMessageBoardMembershipView{value: val, isSet: true}
}

func (v NullableMessageBoardMembershipView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageBoardMembershipView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


