/*
Api Documentation

Api Documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atapi

import (
	"encoding/json"
)

// checks if the SecuritiesAccountDetailsView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecuritiesAccountDetailsView{}

// SecuritiesAccountDetailsView struct for SecuritiesAccountDetailsView
type SecuritiesAccountDetailsView struct {
	ClearingAccountId *string `json:"clearingAccountId,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	PrivateAccount *bool `json:"privateAccount,omitempty"`
	Version *int64 `json:"version,omitempty"`
}

// NewSecuritiesAccountDetailsView instantiates a new SecuritiesAccountDetailsView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecuritiesAccountDetailsView() *SecuritiesAccountDetailsView {
	this := SecuritiesAccountDetailsView{}
	return &this
}

// NewSecuritiesAccountDetailsViewWithDefaults instantiates a new SecuritiesAccountDetailsView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecuritiesAccountDetailsViewWithDefaults() *SecuritiesAccountDetailsView {
	this := SecuritiesAccountDetailsView{}
	return &this
}

// GetClearingAccountId returns the ClearingAccountId field value if set, zero value otherwise.
func (o *SecuritiesAccountDetailsView) GetClearingAccountId() string {
	if o == nil || IsNil(o.ClearingAccountId) {
		var ret string
		return ret
	}
	return *o.ClearingAccountId
}

// GetClearingAccountIdOk returns a tuple with the ClearingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecuritiesAccountDetailsView) GetClearingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClearingAccountId) {
		return nil, false
	}
	return o.ClearingAccountId, true
}

// HasClearingAccountId returns a boolean if a field has been set.
func (o *SecuritiesAccountDetailsView) HasClearingAccountId() bool {
	if o != nil && !IsNil(o.ClearingAccountId) {
		return true
	}

	return false
}

// SetClearingAccountId gets a reference to the given string and assigns it to the ClearingAccountId field.
func (o *SecuritiesAccountDetailsView) SetClearingAccountId(v string) {
	o.ClearingAccountId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SecuritiesAccountDetailsView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecuritiesAccountDetailsView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SecuritiesAccountDetailsView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SecuritiesAccountDetailsView) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SecuritiesAccountDetailsView) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecuritiesAccountDetailsView) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SecuritiesAccountDetailsView) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SecuritiesAccountDetailsView) SetName(v string) {
	o.Name = &v
}

// GetPrivateAccount returns the PrivateAccount field value if set, zero value otherwise.
func (o *SecuritiesAccountDetailsView) GetPrivateAccount() bool {
	if o == nil || IsNil(o.PrivateAccount) {
		var ret bool
		return ret
	}
	return *o.PrivateAccount
}

// GetPrivateAccountOk returns a tuple with the PrivateAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecuritiesAccountDetailsView) GetPrivateAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.PrivateAccount) {
		return nil, false
	}
	return o.PrivateAccount, true
}

// HasPrivateAccount returns a boolean if a field has been set.
func (o *SecuritiesAccountDetailsView) HasPrivateAccount() bool {
	if o != nil && !IsNil(o.PrivateAccount) {
		return true
	}

	return false
}

// SetPrivateAccount gets a reference to the given bool and assigns it to the PrivateAccount field.
func (o *SecuritiesAccountDetailsView) SetPrivateAccount(v bool) {
	o.PrivateAccount = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SecuritiesAccountDetailsView) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecuritiesAccountDetailsView) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SecuritiesAccountDetailsView) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *SecuritiesAccountDetailsView) SetVersion(v int64) {
	o.Version = &v
}

func (o SecuritiesAccountDetailsView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecuritiesAccountDetailsView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClearingAccountId) {
		toSerialize["clearingAccountId"] = o.ClearingAccountId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PrivateAccount) {
		toSerialize["privateAccount"] = o.PrivateAccount
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableSecuritiesAccountDetailsView struct {
	value *SecuritiesAccountDetailsView
	isSet bool
}

func (v NullableSecuritiesAccountDetailsView) Get() *SecuritiesAccountDetailsView {
	return v.value
}

func (v *NullableSecuritiesAccountDetailsView) Set(val *SecuritiesAccountDetailsView) {
	v.value = val
	v.isSet = true
}

func (v NullableSecuritiesAccountDetailsView) IsSet() bool {
	return v.isSet
}

func (v *NullableSecuritiesAccountDetailsView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecuritiesAccountDetailsView(val *SecuritiesAccountDetailsView) *NullableSecuritiesAccountDetailsView {
	return &NullableSecuritiesAccountDetailsView{value: val, isSet: true}
}

func (v NullableSecuritiesAccountDetailsView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecuritiesAccountDetailsView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


